# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    front_url: "https://drbooking.fcpo.agency"
    user_images: "%kernel.project_dir%\\public\\uploads\\user_images"
    service_account_file: '%kernel.project_dir%/config/service-account.json'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # App\Helpers\Helpers: ~
    # App\Controller\UserController:
    #     arguments:
    #         $messaging: '@myProjectMessaging'

    # Custom error controller
    App\Controller\ErrorController:
        tags: ['controller.service_arguments']

    # App\Routing\EntityRouteLoader:
    #     tags:
    #         - { name: routing.loader }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
